import wx
import wx.aui as aui
import wx.stc as stc

APP_NAME = 'Text Editor'

AUTO_INDENT = True
BACKSPACE_UNINDENTS = True
BOOKMARKS = True
BOOKMARK_MARGIN_SIZE = 20
BOOKMARK_SYMBOL = stc.STC_MARK_ARROW
CARET_FOREGROUND = wx.BLACK
CARET_LINE_VISIBLE = True
CARET_LINE_BACKGROUND = '#eeeeee'
CARET_PERIOD = 500
CARET_WIDTH = 1
EDGE_COLUMN = 80
EDGE_MODE = stc.STC_EDGE_LINE
END_AT_LAST_LINE = True
FOLDING = True
FOLDING_MARGIN_SIZE = 12
HIGHLIGHT_SELECTION = True
HIGHLIGHT_SYNTAX = True
INDENTATION_GUIDES = True
LINE_NUMBERS = True
MARGIN_LEFT = 2
MARGIN_RIGHT = 2
MATCH_BRACES = True
SELECTION_BACKGROUND = 'light grey'
SELECTION_FOREGROUND = 'black'
TAB_INDENTS = True
TAB_WIDTH = 4
USE_HORIZONTAL_SCROLL_BAR = False
USE_SELECTION_FOR_F3 = True
USE_TABS = False
VIEW_WHITESPACE = True
WORD_WRAP = False

FONT_FACE = 'Bitstream Vera Sans Mono'
FONT_SIZE = 10
LANGUAGE = 'Python'

AUI_NB_TAB_FIXED_WIDTH = False
AUI_NB_SCROLL_BUTTONS = True
AUI_NB_WINDOWLIST_BUTTON = True
AUI_NB_CLOSE = aui.AUI_NB_CLOSE_BUTTON
#AUI_NB_CLOSE_BUTTON
#AUI_NB_CLOSE_ON_ACTIVE_TAB
#AUI_NB_CLOSE_ON_ALL_TABS
AUI_NB_POSITION = aui.AUI_NB_TOP
#AUI_NB_TOP
#AUI_NB_BOTTOM

MAIN_WINDOW_MAXIMIZED = False
MAIN_WINDOW_PERSISTED = True
MAIN_WINDOW_POSITION = None
MAIN_WINDOW_SIZE = None

ACTIVE_TAB = -1
CLOSE_TAB_ON_DOUBLE_CLICK = True
CREATE_TAB_ON_DOUBLE_CLICK = True
CONFIRM_CLOSE_WITH_EDITS = True
FULL_PATH_IN_TITLE = True
OPEN_FILES = []
SHOW_RECENT_FILES = True
RECENT_FILES = []
RECENT_FILES_DISPLAY = 10
RECENT_FILES_SIZE = 25
REMEMBER_OPEN_FILES = True
SET_DIRECTORY_FOR_OPEN = True
USE_PSYCO = True

FIND_TEXT = ''
FIND_HISTORY = []
FIND_WHOLE_WORD = False
FIND_MATCH_CASE = False
FIND_NORMAL = True
FIND_EXTENDED = False
FIND_REGEX = False
FIND_CLOSE_DIALOG = False
FIND_DOWN = True
FIND_WRAP = True

PYTHON_KEYWORDS = \
'''
and       del      from    not     while
as        elif     global  or      with
assert    else     if      pass    yield
break     except   import  print
class     exec     in      raise
continue  finally  is      return
def       for      lambda  try
False     True     None
'''
